---
title: "List columns"
author: "Derek Lamb"
date: "`r Sys.Date()`"
output: github_document
---

```{r load packages, message = FALSE}
library(tidyverse)
library(rvest)

# Set default figure options
knitr::opts_chunk$set(
  fig.width = 6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

# set seed for consistency
set.seed(12345)
```

### Lists
```{r df}
vec_numeric = 1:4
vec_char = c("my", "name", "is", "jeff")

tibble(
  num = vec_numeric,
  char = vec_char
)


```

## Mean and sd function
```{r function def}
mean_and_sd = function(x) {

  if (!is.numeric(x)){
    stop("Argument should be numbers")
  }
  else if (length(x) < 2){
    stop("You need at least two numbers to get standard deviations")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

Different stuff with different lengths

```{r}
l = list(
  vec_numeric = 1:5,
  vec_char = LETTERS,
  matrix = matrix(1:9, nrow = 3),
  summary = summary(rnorm(100))
)
```

Accessing lists
```{r accessing lists}
l$vec_char
l[[1]]
l[["summary"]]
```

### Loops

```{r}
list_norm = list(
  a = rnorm(20, 1, 5),
  b = rnorm(20, 0, 7),
  c = rnorm(20, 20, 1),
  d = rnorm(20, -45, 13)
)
```

```{r}
mean_and_sd(list_norm$a)
mean_and_sd(list_norm$b)
mean_and_sd(list_norm$c)
mean_and_sd(list_norm$d)
```

```{r for loop}
# the output vector is needed otherwise nothing will print/be stored
output = vector("list", length = 4)

# basic for loops
for (i in 1:4){
  output[[i]] = mean_and_sd(list_norm[[i]])
}
```

### Now with `map`
```{r map}
output = map(list_norm, mean_and_sd)
output = map(list_norm, median)
output = map(list_norm, summary)
```


# List columns
### create df

```{r create df_listcol}
df_listcol = tibble(
  name = c("a", "b", "c", "d"),
  samp = list_norm
)

```

```{r apply functions to listcol}
mean_and_sd(df_listcol$samp[[1]])

map(df_listcol$samp, mean_and_sd)

df_listcol |> 
  mutate(mean_sd = map(samp, mean_and_sd),
         median = map(samp, median)) |> 
  select(name, mean_sd) |> 
  unnest(mean_sd)
# unnest() turns tibble into sets of lists
```

### NSDUH
```{r nsduh reader function}
nsduh_reader = function(n_table, outcome_name, url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm") {
  
  df = 
    read_html(url) |> 
    html_table() |> 
    nth(n_table) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent),
      outcome = outcome_name) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
  return(df)
}
```

### import data with `for` loop

```{r}
table_input = list(1, 4, 5)
name_input = list("marj", "cocaine", "heroin")

output = vector("list", length = 3)

for (i in 1:3){
  
  output[[i]] = nsduh_reader(n_table = table_input[[i]], 
                             outcome_name = name_input[[i]])
  
}

df_nsduh = bind_rows(output)
```

Try again, using maps!!
```{r}

```


