---
title: "Writing Functions"
author: "Derek Lamb"
date: "`r Sys.Date()`"
output: github_document
---

```{r load packages}
library(tidyverse)
library(rvest)
library(knitr)

# Set default figure options
opts_chunk$set(
  fig.width = 6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Set seed for reproducibility.

```{r set seed}
set.seed(12345)
```


## Z score function
Z scores subtract the mean and devide by the sd.

```{r z score function}
x_vec <- rnorm(20, mean = 5, sd = 0.3)
```

```{r}
(x_vec - mean(x_vec))/sd(x_vec)
```

Write a function to do this!
```{r}
z_score = function(x) {
  
  if (!is.numeric(x)){
    stop("Argument should be numbers")
  }
  else if (length(x) < 2){
    stop("You need at least two numbers to get z scores")
  }
  
  z = (x - mean(x)) / sd(x)
  return(z)
}
```

Check that this works.

```{r}
z_score(x = x_vec)
```

Keep checking

```{r, error = TRUE}
z_score(x = 3)

z_score(c("My", "name", "is", "Jeff"))

z_score(c(TRUE, TRUE, FALSE, TRUE))

z_score(iris)
```

### Multiple outputs

Write a function that returns the mean and sd from a sample.
```{r}
mean_and_sd = function(x) {

  if (!is.numeric(x)){
    stop("Argument should be numbers")
  }
  else if (length(x) < 2){
    stop("You need at least two numbers to get standard deviations")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

Double check this works
```{r}
mean_and_sd(x_vec)
```


### Start geting means and sds

```{r}

x_vec = rnorm(n = 30, mean = 5, sd = 0.5)

  tibble(
    mean = mean(x_vec),
    sd = sd(x_vec)
  )

```

Let's write a function that uses `n`, a true mean, and a true sd as inputs.

```{r}
sim_mean_sd = function(n_obs, mu = 5, sigma = 1){

  x_vec = rnorm(n = n_obs, mean = mu, sd = sigma)

  tibble(
    mean = mean(x_vec),
    sd = sd(x_vec)
  )
  
}
```

```{r}
sim_mean_sd(n_obs = 50)

sim_mean_sd(mu = 12,n_obs = 24,4)
```


